FROM shovalmishal/detr:base

CMD ["/bin/bash", "-c", "python FineTuning.py --backbone resnet101 --dataset_path /storage/shoval/detr/input/dota_dataset --output_dir /storage/shoval/detr/output_detr_DC5_R101 --batch_size 1 --dilation --num_workers 1"]
