FROM shovalmishal/detr:base

CMD ["/bin/bash", "-c", "python FineTuning.py --dataset_path /storage/shoval/detr/input/dota_dataset --output_dir /storage/shoval/detr/output --resume /storage/shoval/detr/output/checkpoint0299.pth --batch_size 12 --num_workers 12"]
